### ISSUE TITLE
Segmentation fault during preprocessing (xyz)

### ISSUE THREAD

**Issue by Kyvala** [MDIL-SNU/SIMPLE-NN_v2#108]
Hello, I'm testing simpleNN, but unfortunately, I can't proceed with the Preprocessing step. I always encounter a "Segmentation fault (core dumped)" error, and I'm certain that it's not due to a lack of memory. I have tested it on a very small subset of the dataset and with a small (testing) number of symmetry functions. The tutorial works fine for me. Could you please assist me in identifying the problem?

**params_X**
2 1 0 6.0 0.003214 0.0 0.0
2 2 0 6.0 0.003214 0.0 0.0
2 3 0 6.0 0.003214 0.0 0.0
2 4 0 6.0 0.003214 0.0 0.0
4 1 1 6.0 0.000357 1.0 -1.0
4 2 2 6.0 0.000357 1.0 -1.0
4 3 3 6.0 0.000357 1.0 -1.0
4 4 4 6.0 0.000357 1.0 -1.0

**input.yaml**
generate_features: True
preprocess: True 
train_model: False
random_seed: 123

params:
    H: params_H
    N: params_N
    C: params_C
    O: params_O

data:
    type: symmetry_function
    absolute_path: False
    refdata_format: xyz
    read_stress: False

preprocessing:
    valid_rate: 0.1
    calc_scale: True
    calc_pca: False

**dataset**
https://pubs.acs.org/doi/suppl/10.1021/acs.jctc.1c00647/suppl_file/ct1c00647_si_002.zip

**structure_list**
./train_300K.xyz :

**Comment by Seungwoo-Hwang** [comment]
Hello, Kyvala.

Thank you for using our package. We found that your error was caused by using data in a different format than VASP. Our code is primarily developed to simulate a periodic boundary system using VASP, so we apologize for the inconvenience if you are using a different type of data format. We are not familiar with handling other types of data. However, we made a simple modification to get the code to work with your data.

There are a few steps required to make it run. Here are the instructions.
1. For reading energy & forces information using the ASE package, you need to change the data format from 'xyz' to 'extxyz' (just change the file name)
2. Since our code is intended to simulate a periodic boundary condition system, you need to change all the pbc tags in the extxyz files from 'F' to 'T'. I think that the simulation cells in your data are large enough that your results are not affected by the PBC condition.
3. We modified our codes, please download the updated SIMPLE-NN.

If you have any other questions, feel free to ask!

Best regards,
Seungwoo.
